version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn add selenium-standalone
      - run: yarn add chromium
      - run: apt-get install chromium-chromedriver
      - run: ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver
      - run: yarn test
